version: 2

models:
  - name: stg_reviews
    description: "Staging model for reviews data with soft-deleted records filtered out"
    columns:
      - name: survey
        description: Type of survey (may contain null values)
      - name: rating
        description: Rating value
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
                quote: false
      - name: _fivetran_deleted
        description: Fivetran soft delete flag

