version: 2

models:
  - name: surveys_avgs
    description: "Aggregated average ratings by survey type"
    columns:
      - name: survey
        description: Type of survey (may contain null values for reviews without survey type)
        tests:
          - unique
      - name: average_rating
        description: Average rating for the survey type
        tests:
          - not_null

